### ISSUE TITLE
Design for orthographic camera

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#103]
## Use Case
As a user viewing a trajectory in the viewer, I want to be able to switch the camera to orthographic view so that I can see spatial relationships without distortion from perspective.

## Acceptance Criteria
UI controls on the viewer allow a user to toggle back and forth between ortho and perspective camera modes.

## Details
This can be really useful for seeing how objects receding into the distance line up in the plane of the screen.

[orthographic projection wiki](https://en.wikipedia.org/wiki/Orthographic_projection)

**Comment by lynwilhelm** [comment]
This dev work might fit nicely with https://github.com/simularium/simularium-website/issues/320
