### ISSUE TITLE
UI/UX Design for interactive publication

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#137]
## Use Case
As a user, I want to explore an interactive web publication to learn about a biology topic in order to imagine how the Simularium viewer could be used for communication of research or education.

## Acceptance Criteria
Design for a website with multiple types of embedded content (images, movies, interactive modules incl Simularium viewer) and links that explain a concept from published paper(s) and allows users to interactively explore and learn about it by active experimentation.

When complete, add design specifications to [this issue](https://github.com/simularium/simularium-planning/issues/138).

## Details
This depends on final content https://github.com/simularium/simularium-planning/issues/136

**Comment by lynwilhelm** [comment]
Dev link to final designs: https://www.figma.com/file/KEEHjYRxL9ouTuceTtyC7G/2023-July-Interactive-Publication?type=design&node-id=842%3A119426&mode=dev
