### ISSUE TITLE
Research getting started experience

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#144]
## Use Case
As a product owner, I want to know more about users' experience using Simularium for the first time and get ideas for ways to improve that experience.

## Acceptance Criteria
Report to the Simularium team on current getting started experience and ideas for improvement.

## Details
This experience is different for different users, e.g. computational users will get started in Python and other users will explore UI on the website.

**Comment by TravisKroeker** [comment]
Implementation set for early September. Travis to prepare a few options for designs and a small interview script to speak to Julie, Saurabh, and Jess Yu including walking through designs at end. Then iterate a final version due the first week of August. 

Hand off to Megan. Joe will likely take point on front-end

**Comment by lynwilhelm** [comment]
@TravisKroeker I think this ticket has pretty good coverage with the research done for "First-time mobile visitors", combined with the UX team efforts in auditing and examining "onboarding/user support" discovery work. One additional thing that could be done is to journey map both computational and wet lab experiences. The wet lab one might be more hypothetical if we want to include live mode (live adjustments of parameters), which is kind of the meat of the wet lab use case.

**Comment by blairlyons** [comment]
@lynwilhelm is there more work we want to do on this ticket right now, or do we leave it with the overlap from https://github.com/simularium/simularium-planning/issues/143?

**Comment by lynwilhelm** [comment]
@blairlyons I think we are good on it for now, so I'm going to close it. If we want to research anything more specific and targeted around getting started in the future, I'm game! We could also brainstorm a little further based on mobile discoveries to commit to specific initiative of improvement.
