### ISSUE TITLE
Design to generate embed code snippet

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#145]
## Use Case
As a user, I want to be able to generate a code snippet I can use to embed a Simularium viewer with my trajectory loaded in another website.

## Acceptance Criteria
Design specification for a menu to generate code snippets.

When complete, add spec to [this issue](https://github.com/simularium/simularium-planning/issues/146).

## Details
A new menu option or button could open a panel to get a .simularium file URL from the user (unless this is already a trajectory loaded from a URL) and generate iframe code they can copy and paste into their own website to display the viewer loaded with that trajectory.

**Comment by jsavieo** [comment]
@jsavieo to extend through Q4

**Comment by blairlyons** [comment]
modal needs:
- area for code preview
- heading
- time to start at
- embed window size
