### ISSUE TITLE
Implement generate embed code snippet

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#146]
## Use Case
As a user, I want to be able to generate a code snippet I can use to embed a Simularium viewer with my trajectory loaded in another website.

## Acceptance Criteria
Design is complete and can be found in the [master components file for Simularium](https://www.figma.com/design/u4lZYuVwbsFpzBikgwAVRb/Master-components-Simularium?node-id=0-1&t=EctHHULwViv17z1e-0)

- Update share modal to match spec to accommodate new functionality
- Update global modal styling to new heading style, updates include:
- - New heading style
- - Larger close button "x"
- -See dependent tickets below

Related/dependent tickets:
https://github.com/simularium/simularium-website/issues/533
https://github.com/simularium/simularium-website/issues/534

**Comment by lynwilhelm** [comment]
@interim17 @blairlyons Design is complete. I will close out the UX ticket for this now. This design is dependent two other tickets, called out above.
