### ISSUE TITLE
Fix actions auth errors

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#154]
## What needs to happen?
With recent changes to linking github accounts for the institute, a bunch of actions are failing with: "Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization." I'm not sure if this needs to be done on a per account basis, if that's the case we need instructions for everyone on how to do this.

## Why should we do this?
We need our actions to work.

## When does this need to get done?
Early July 2023

**Comment by ascibisz** [comment]
I believe this is something that a simple configuration change to our github enterprise settings will fix (based on reading [this](https://docs.github.com/en/github-ae@latest/admin/github-actions/managing-access-to-actions-from-githubcom/about-using-actions-in-your-enterprise#configuring-access-to-actions-on-githubcom)). However, I do not have an admin account so I can't do this independently. I'll go to Software Engineering Office Hours on Wednesday and try to get this sorted

**Comment by ascibisz** [comment]
Tracked in ServiceNow ticket: [INC0011051](https://alleninstitute.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3D2af3aa8c9704b150550d11b00153af2a%26sysparm_stack%3Dincident_list.do%3Fsysparm_query%3Dactive%3Dtrue)

**Comment by ascibisz** [comment]
Alright everything is all good! The last step was updating the relevant personal access tokens associated with secrets referenced in the actions to have SSO properly configured. I just generated a new personal access token and updated the simularium secret, and now that seems to be all good! If there are any other actions that are failing that use a different secret, all one has to do is make sure the token that is affiliated with it has single sign on authorized for the relevant project.
