### ISSUE TITLE
Prepare example models 1

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#35]
- [x] https://github.com/simularium/simularium-website/issues/326
- [x] https://github.com/simularium/simulariumio/issues/40

## Use Case
As a user of the Viewer website, I want to see example trajectories from Vivarium, that include PDB geometry, and from ME Johnson et al paper discussing when spatial simulation is needed.

## Acceptance criteria
- .simularium file for Vivarium E coli is posted
- .simularium file(s) with PDB geometry are posted
- .simularium file(s) from ME Johnson et al are posted

**Comment by jsavieo** [comment]
@blairlyons and @jsavieo to work on paring this back
