### ISSUE TITLE
Demonstrate streaming with octopus (Python engine)

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#51]
- [x] https://github.com/simularium/vivarium-models/issues/14
- [x] https://github.com/simularium/simularium-viewer/issues/275
- [x] https://github.com/simularium/octopus/issues/3
- [x] https://github.com/simularium/octopus/issues/1
- [x] https://github.com/simularium/octopus/issues/4

## Use Case
As a developer, I want to see simulations streaming from the new Python engine (octopus) to the Simularium viewer, both from pre-computed files and live simulations running in Vivarium.

## Acceptance Criteria
- Initial octopus Python engine, deployed in cloud
- Demonstrate streaming data to clients over websockets on request
- Demonstrate streaming data from a pre-computed file
- Demonstrate streaming data from a vivarium simulation
- Test for max concurrent users

**Comment by jsavieo** [comment]
@toloudis and @blairlyons divide up this milestone to make vivarium a separate story
