### ISSUE TITLE
Create Python server for octopus, autoconversion, and analysis

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#67]
## Use case
As a developer working on octopus streaming, analysis, and autoconversion, I want a Python server in AWS.

## Acceptance Criteria
A python server exists that can be deployed to.

## Details
Autoscaling is out of scope, this is just one server node that we can access by IP, likely EC2?

Work with software on this.

**Comment by ascibisz** [comment]
Software JIRA ticket for tracking this work: https://aicsjira.corp.alleninstitute.org/browse/SWE-463

**Comment by ascibisz** [comment]
We've got the EC2 instance up and running and I just manually deployed octopus to it and was able to get a test smoldyn file to get converted via the example UI!

Server IP address: 18.223.108.15
Name: aics-octopus
AWS account: aics-ac
AWS region: us-east-2
Instance type: r5b.large

Still plenty of work to do (including getting a formal deployment process setup, run more testing, etc), but I think we've made enough progress to close this ticket out.
