### ISSUE TITLE
Deploy octopus, autoconversion, and analysis to server

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#93]
## Use Case
As a developer, I want octopus with autoconversion and analysis to be deployed to a server so that I can test remotely.

## Acceptance Criteria
Provide info needed to connect to server that accepts octopus, autoconversion, and analysis websocket messages.

## Details
octopus plus autoconversion scripts from the lambda and the metrics-calculator dependency

**Comment by ascibisz** [comment]
Deployment instructions: https://docs.google.com/document/d/1JS56NCi5_w3A0dG5c4cwCL7pqMt-RKASw7nU5qLqIEM/edit#
